# 只为下记QQ群成员提供服务
active-groups:
  - 0123456789
  - 0123456789

bot-qq: 0123456789 # 机器人QQ号

# 验证码
captcha:
  expire: 300 # 秒 后过期
  length: 4 # 位 长度
  type: 0 # 0: 数字 1: 字母 2: 数字+字母 3: 自定义字符 类型
  custom: "0123456789" # 自定义字符